### PR TITLE
Thick and Thin options for fontWeight

### PR DESCRIPTION
**Pull request by hammadj**

### CODE REVIEW

**Comment by bmcmahen** [comment]
I think we should enforce an eslint coding style. I don't use semi-colons anywhere in this project, and I think we should maintain that consistency.

**Comment by bmcmahen** [comment]
I'll add a linter with some rules that I think should remain consistent project-wide.

**Comment by hammadj** [comment]
Yea I agree, I was just gonna mention that haha. In my personal projects I use eslint with the babel-eslint parser and the airbnb preset (https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb). I think it would be best to start with that and then customize it how you want.

**Comment by bmcmahen** [comment]
Just configured it, and added it to master. I made a few changes to the airbnb preset so that it won't drive me totally crazy, but let me know if you'd like any changes.

**Comment by hammadj** [comment]
looks good! You might also want to disable the unterminated statements warning

**Pull request merged**
